# Use user/saltanadev123 user/password credentials
version: "3.1"

services:
  web:
    image: saltanahq/kisse
    restart: always
    ports:
      - "3000:3000"

    env_file:
      - .env
      - .env.local
    build:
      dockerfile: Dockerfile
      args:
        - GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN}
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-saltana}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-saltanadev123}"

volumes:
  pgdata:
